name: grvTags
version: 1.0
main: gc.grivyzom.grvTags
api-version: 1.13
author: Brocolitx
description: Sistema completo de tags con categorías y MySQL

commands:
    tag:
        description: Comando principal de tags - Abre el GUI de selección de tags
        usage: /<command>
        aliases: [tags]
    category:
        description: Comando para gestionar categorías - Abre el GUI de categorías (Solo OP)
        usage: /<command>
        aliases: [categorias, cat]
        permission: op
    grvTags:
        description: Comando de administración del plugin
        usage: |
            /<command> [subcomando]
            Subcomandos disponibles:
            - reload: Recarga configuraciones
            - info: Información del plugin
            - database: Estado de la base de datos
            - create <nombre> <categoria>: Crear un tag
            - createcategory <nombre>: Crear una categoría
            - editor <category|tag|tags>: Abrir editores
            - help: Mostrar ayuda
        aliases: [grvtags, grv]
        permission: op

permissions:
    grvtags.admin:
        description: Acceso completo a comandos de administración
        default: op
    grvtags.use:
        description: Uso básico del plugin (comando /tags)
        default: true

softdepend: [Vault, PlaceHolderApi]